name: EKAT Telegram Bot

on:
  schedule:
    - cron: "0 7 * * *"  # Her gün Türkiye saatiyle 10:00 (UTC+3 = 07:00 UTC)
  workflow_dispatch:      # Manuel başlatmak için

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Botu çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python ekat_bot.py
