name: EKAT Bot Kontrol

on:
  schedule:
    - cron: "0 * * * *"  # Her saat başında
  workflow_dispatch:      # Manuel çalıştırma seçeneği
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Repo çekiliyor
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Kütüphaneler yükleniyor
        run: pip install -r requirements.txt

      - name: Bot çalıştırılıyor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python ekat_bot.py
